solution for 04-SPA/01-05
js-tasks-ru/vue-20210119_alyona75 pull request #6
Opened 2021-02-16 16:02 UTC by alaroma

2021-02-16 16:02 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-02-17 10:14 UTC, ShGKme requested changes
Требуется небольшое исправление в `BaseLayout`.
В остальных компонентах шаблонах можно также немного поправить вёрстку, чтобы она совпадала.
Решение в `ScrollBehavior` формально работать, но требует для такого решения редактирования конфигурации роутера (либо обновления решения).

2021-02-17 10:14 UTC, ShGKme commented on 04-SPA/03-NotFound/router/index.js
> +    },
Такие маршруты лучше описывать в конце.

2021-02-17 10:14 UTC, ShGKme commented on 04-SPA/02-ScrollBehavior/router/index.js
> +  else if (to.meta.saveScrollPosition && from.meta.saveScrollPosition) return false;
Такое решение допустимо, но работать оно будет только, если мета-свойство есть у ВСЕХ маршрутов, к которым должно работать отключение скролла. В текущем примере их нет. Требуется либо добавить в описание маршрутов мета свойства и дочерним маршрутам, чтобы они были у всех маршрутов, либо изменить код функции так, чтобы отключение прокрутки работало, когда мета свойство установлено у одного из маршрутов в цепочке (у общего родительского маршрута). В последнем поможет свойство `matched` у маршрута, возвращающее массив всех маршрутов.

Сейчас, если протестировать компонент вручную, он работать не будет.

2021-02-17 10:14 UTC, ShGKme commented on 04-SPA/04-Layouts/components/BaseLayout.vue
> +      <router-view />
`BaseLayout` работает также, как остальные шаблоны - является лишь обёрткой, с общими частями страницы для всех страниц. Содержимое страницы передаётся через слот.

2021-02-17 10:14 UTC, ShGKme commented on 04-SPA/04-Layouts/components/AuthLayout.vue
> +</div>
Чуть-чуть не совпадает с разметкой:
https://github.com/js-tasks-ru/vue-course-materials/blob/master/meetups-markup/meetup-form.html#L29-L31

2021-02-17 10:14 UTC, ShGKme commented on 04-SPA/04-Layouts/components/FormLayout.vue
> +  </div>
Аналогично, чуть-чуть не совпадает с версткой.
https://github.com/js-tasks-ru/vue-course-materials/blob/master/meetups-markup/meetup-form.html#L29-L31

2021-02-17 11:27 UTC, ShGKme approved these changes
Все задачи приняты 👍

2021-02-17 11:29 UTC, merged