solutions for 06-deep-vue/01-03 & 07-forms/01-02
js-tasks-ru/vue-20210119_alyona75 pull request #7
Opened 2021-02-21 15:44 UTC by alaroma

2021-02-21 15:44 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-02-22 11:57 UTC, ShGKme requested changes
Требуется небольшое исправление в `DateInput`, все остальные задачи приняты.

2021-02-22 11:57 UTC, ShGKme commented on 06-deep-vue/01-Buttons/components/BaseButton.vue
> +  }
Отслеживание здесь не требуется

2021-02-22 11:57 UTC, ShGKme commented on 06-deep-vue/03-DateInput/components/DateInput.vue
> +      }
Это мутация входного параметра... Здесь оно не приводит к ошибке, но так делать не хорошо, это может привести к ошибкам в будущем.

2021-02-23 18:01 UTC, ShGKme approved these changes
Принято 👍

2021-02-23 18:01 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- package.json — изменен
```

2021-02-23 18:09 UTC, ShGKme commented on 07-forms/04-GeneratedForm/components/MeetupAgendaItemForm.vue
> +        v-on:[data.model.event]='getEventHandler'
Нужна ли эта обработка события, если уже есть отслеживание за `agendaItem_`?

2021-02-23 18:12 UTC, alaroma commented on 07-forms/04-GeneratedForm/components/MeetupAgendaItemForm.vue
> +        v-on:[data.model.event]='getEventHandler'
> 
> 
> Нужна ли эта обработка события, если уже есть отслеживание за `agendaItem_`?

да, не нужна. Сейчас поправлю)

2021-02-23 19:18 UTC, ShGKme approved these changes

2021-02-23 19:20 UTC, merged